dir = "@ALIVE_the-star";
name = "Arma 3: ALiVE, the-star fork";
picture = "x\alive\addons\main\logo_alive.paa";
actionName = "$STR_MOD_LAUNCHER_ACTION";
action = "http://alivemod.com";
description = "Exclude Custom Military Objective";
hideName = 1;
hidePicture = 0;
logo = "x\alive\addons\ui\logo_alive_crop.paa";
logoOver = "x\alive\addons\ui\logo_alive_crop.paa";
tooltip = "ALiVE Mod, the-star fork";
tooltipOwned = "ALiVE Mod Owned! the-star fork";
overview = "Exclude Custom Military Objective Testing";
author = "ALiVE Mod Team";
overviewPicture = "x\alive\addons\main\logo_alive.paa";
overviewText = "Exclude Custom Military Objective Testing";
overviewFootnote = "<br /><br /><t color='#999999'>This content is under Attribution-NonCommercial-NoDerivs 3.0 Unported License.<br />Press <t /><t color='#19d3ff'>Left Shift + P<t /><t color='#999999'> to open the store page for more information.<t />";
